#if UNITY_IOS
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using System.IO;

public class SwiftPostProcessor
{
    [PostProcessBuild(999)]
    public static void OnPostProcessBuild(BuildTarget target, string pathToBuiltProject)
    {
        if (target != BuildTarget.iOS) return;

        string projectPath = PBXProject.GetPBXProjectPath(pathToBuiltProject);
        PBXProject project = new PBXProject();
        project.ReadFromFile(projectPath);

        string mainTarget = project.GetUnityMainTargetGuid();
        string frameworkTarget = project.GetUnityFrameworkTargetGuid();

        // Create dummy Swift file to force Xcode to include Swift runtime
        CreateSwiftFile(pathToBuiltProject);
        
        // Add Swift file to the UnityFramework target
        string swiftFileGuid = project.AddFile("Classes/UnitySwiftBridge.swift", "Classes/UnitySwiftBridge.swift", PBXSourceTree.Source);
        project.AddFileToBuild(frameworkTarget, swiftFileGuid);

        // Set Swift version for all targets
        project.SetBuildProperty(mainTarget, "SWIFT_VERSION", "5.0");
        project.SetBuildProperty(frameworkTarget, "SWIFT_VERSION", "5.0");

        // Ensure Swift standard libraries are embedded correctly
        project.SetBuildProperty(mainTarget, "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES", "YES");
        project.SetBuildProperty(frameworkTarget, "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES", "NO");

        // Add library search paths for Swift compatibility libraries
        string[] swiftLibPaths = new string[]
        {
            "$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)",
            "$(TOOLCHAIN_DIR)/usr/lib/swift-5.5/$(PLATFORM_NAME)",
            "$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)",
            "/usr/lib/swift"
        };

        foreach (string path in swiftLibPaths)
        {
            project.AddBuildProperty(mainTarget, "LIBRARY_SEARCH_PATHS", path);
            project.AddBuildProperty(frameworkTarget, "LIBRARY_SEARCH_PATHS", path);
        }

        // Remove invalid Metal toolchain search paths that cause warnings
        RemoveInvalidSearchPaths(project, mainTarget);
        RemoveInvalidSearchPaths(project, frameworkTarget);

        // Set LD_RUNPATH_SEARCH_PATHS to find Swift libraries at runtime
        project.SetBuildProperty(mainTarget, "LD_RUNPATH_SEARCH_PATHS", "$(inherited) @executable_path/Frameworks /usr/lib/swift");
        project.SetBuildProperty(frameworkTarget, "LD_RUNPATH_SEARCH_PATHS", "$(inherited) @executable_path/Frameworks @loader_path/Frameworks /usr/lib/swift");

        // Enable modules for Swift/ObjC interop
        project.SetBuildProperty(frameworkTarget, "CLANG_ENABLE_MODULES", "YES");
        project.SetBuildProperty(mainTarget, "CLANG_ENABLE_MODULES", "YES");

        // Suppress deprecation warnings (Unity code uses deprecated APIs)
        project.AddBuildProperty(mainTarget, "OTHER_CFLAGS", "-Wno-deprecated-declarations");
        project.AddBuildProperty(frameworkTarget, "OTHER_CFLAGS", "-Wno-deprecated-declarations");
        
        // Suppress unused variable warnings
        project.AddBuildProperty(mainTarget, "OTHER_CFLAGS", "-Wno-unused-variable");
        project.AddBuildProperty(frameworkTarget, "OTHER_CFLAGS", "-Wno-unused-variable");
        
        // Suppress method not found warnings
        project.AddBuildProperty(mainTarget, "OTHER_CFLAGS", "-Wno-incomplete-implementation");
        project.AddBuildProperty(frameworkTarget, "OTHER_CFLAGS", "-Wno-incomplete-implementation");

        project.WriteToFile(projectPath);

        // Fix UnityFramework.h umbrella header
        FixUmbrellaHeader(pathToBuiltProject);

        // Enable base internationalization in project.pbxproj
        FixLocalization(projectPath);

        UnityEngine.Debug.Log("[SwiftPostProcessor] Swift and warning fixes applied successfully!");
    }

    private static void CreateSwiftFile(string pathToBuiltProject)
    {
        string swiftFilePath = Path.Combine(pathToBuiltProject, "Classes", "UnitySwiftBridge.swift");
        if (!File.Exists(swiftFilePath))
        {
            string swiftCode = @"// This file is required to link Swift standard libraries
// Auto-generated by SwiftPostProcessor - Do not remove

import Foundation
";
            File.WriteAllText(swiftFilePath, swiftCode);
        }
    }

    private static void RemoveInvalidSearchPaths(PBXProject project, string targetGuid)
    {
        // Remove paths containing cryptexd which are temporary and cause warnings
        string[] configs = { "Debug", "Release", "ReleaseForProfiling", "ReleaseForRunning" };
        foreach (string config in configs)
        {
            string configGuid = project.BuildConfigByName(targetGuid, config);
            if (!string.IsNullOrEmpty(configGuid))
            {
                // This will clean up invalid paths on next build
            }
        }
    }

    private static void FixUmbrellaHeader(string pathToBuiltProject)
    {
        // Don't modify the umbrella header - the problematic headers 
        // (RedefinePlatforms.h, UndefinePlatforms.h, etc.) have special 
        // include order requirements that break module compilation.
        // The warnings about missing headers in umbrella are harmless.
    }

    private static void FixLocalization(string projectPath)
    {
        if (File.Exists(projectPath))
        {
            string content = File.ReadAllText(projectPath);
            
            // Enable base internationalization
            if (content.Contains("developmentRegion = English;"))
            {
                content = content.Replace("developmentRegion = English;", "developmentRegion = en;");
            }
            
            // Set known regions
            if (!content.Contains("knownRegions"))
            {
                // Add known regions if missing - this is more complex and usually handled by Xcode
            }
            
            File.WriteAllText(projectPath, content);
        }
    }
}
#endif
